import Head from "next/head";
import { StoreContext } from "@/contexts/storeContext";
import { useContext, useEffect, useState } from "react";
import styles from "@/styles/Basket.module.css";
import { Button, message, Space } from "antd";

export default function BookingInfo(props) {
  const state = useContext(StoreContext);
  const [totalAmount, setTotalAmount] = useState(0);
  const [totalPrice, setTotalPrice] = useState(0);
  const { data } = useContext(StoreContext);

  useEffect(() => {
    let amount = 0;
    let price = 0;

    data.basket.forEach((item) => {
      amount += item.amount;
      price += item.price * item.amount;
    });

    setTotalAmount(amount);
    setTotalPrice(price);
  }, [data.basket]);

  /* verification message */
  const [messageApi, contextHolder] = message.useMessage();
  const success = () => {
    messageApi.open({
      type: "success",
      content: "Verified!",
    });
  };

  const handleSubmit = (e, ticketType) => {
    e.preventDefault(); // Prevent form submission
    success();

    //setting booking info per ticket
    const personalInfo = {
      firstName: e.target.elements.firstName.value,
      lastName: e.target.elements.lastName.value,
      email: e.target.elements.email.value,
      birthDate: e.target.elements.birthDate.value,
      ticket: ticketType,
    };

    props.setInfo((old) => old.concat(personalInfo));
  };

  return (
    <>
      {contextHolder}
      <Head>
        <title>fooFest</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.wrapper}>
        <h1 style={{ fontSize: "2.25rem" }}>Booking Information</h1>
        <ul>
          {state.data.basket.map((item) => (
            <li className={styles.ticketFormList} key={item.id}>
              {item.name} × {item.amount}
              {[...Array(item.amount)].map((_, index) => (
                <form
                  onChange={() => {
                    console.log(item.name);
                  }}
                  onSubmit={(e) => {
                    handleSubmit(e, item.name);
                  }}
                  className={styles.userInfoForm}
                  key={`${item.id}-${index}`}
                >
                  <p>
                    {item.name} {index + 1}
                  </p>
                  <div className={styles.formContainer}>
                    <div>
                      <div className={styles.labelAndInput}>
                        <label>First Name</label>
                        <input type="text" name="firstName" placeholder="John" required />
                      </div>
                      <div className={styles.labelAndInput}>
                        <label>E-mail</label>
                        <input
                          type="email"
                          name="email"
                          placeholder="example@foofest.com"
                          required
                        />
                      </div>
                    </div>
                    <div>
                      <div className={styles.labelAndInput}>
                        <label>Last Name</label>
                        <input type="text" name="lastName" placeholder="Smith" required />
                      </div>

                      <div className={styles.labelAndInput}>
                        <label>Date of Birth</label>
                        <input type="date" name="birthDate" placeholder="Write here.." required />
                      </div>
                    </div>
                  </div>
                  <input type="submit" value="Verify" />
                </form>
              ))}
            </li>
          ))}
        </ul>
      </div>
    </>
  );
}
