
import Head from 'next/head'
import { StoreContext } from '@/contexts/storeContext';
import { useContext } from 'react';

export default function Checkout() {
  const state = useContext(StoreContext);    
  const {basket} =state;

  return (
    <>
      <Head>
        <title>fooFest</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<div className='Checkout'>
  <ul>
    {state.data.basket.map((item)=>(
    <li>
        {item.name} X {item.amount}
        </li>
        ))}
  </ul>
<form>
    <label>Name
        <input type="text" name="name" required/>
    </label>
    <label>E-mail
        <input type="email" name="email" required/>
    </label>
    <button>Buy now</button>
</form>

</div>
    </>
  );
}