
import Head from 'next/head'


export default function Home({data}) {
  return (
    <>
      <Head>
        <title>fooFest</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<div className='Home'>
  <article>
    
  </article>
</div>
    </>
  );
}
