import Head from "next/head";
import styles from "@/styles/Program.module.css";
import { Navbar } from "./components/Navbar";
import { Newsletter } from "./components/Newsletter";
import { Footer } from "./components/Footer";
import OneDaySchedule from "./components/OneDaySchedule";

export default function Program() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.Header}>
        <Navbar />
      </header>
      <main className={styles.Main}>
        <h1>PROGRAM</h1>
        <OneDaySchedule />
        <Newsletter />
      </main>
      <footer>
        <Footer />
      </footer>
    </>
  );
}
