import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useState, useEffect } from "react";

export default function ThankYou() {
  const [data, setData] = useState([]);

  return (
    <>
      <Head>
        <title>fooFest</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.thankYouContainer}>
        <svg
          xmlns="http://www.w3.org/2000/svg"
          width="52"
          height="52"
          fill="currentColor"
          class="bi bi-check-circle"
          viewBox="0 0 16 16"
          style={{ backgroundColor: "#DFFE00", borderRadius: "50px" }}
        >
          <path d="M10.97 4.97a.235.235 0 0 0-.02.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-1.071-1.05z" />
        </svg>
        <h2 className={styles.written}>Thank you!</h2>
        <h4>
          We've sent you an email with all your ticket information. <br />{" "}
          Follow us to stay updated!
        </h4>

        <p>
          Your order number is: <strong>3627438</strong>
        </p>
      </div>
    </>
  );
}
